# Generated by Django 2.1.1 on 2018-11-11 05:36

from django.db import migrations, models
import django.db.models.deletion
import grades.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id_curso', models.AutoField(primary_key=True, serialize=False)),
                ('nm_curso', models.CharField(max_length=50, verbose_name='Nome do Curso')),
                ('sigla_curso', models.CharField(max_length=5, verbose_name='Sigla do Curso')),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id_disciplina', models.AutoField(primary_key=True, serialize=False)),
                ('nm_disciplina', models.CharField(max_length=50, verbose_name='Nome da Disciplina')),
                ('sigla_disciplina', models.CharField(max_length=5, verbose_name='Sigla da Disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='Disponibilidade',
            fields=[
                ('id_disponibilidade', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id_grade', models.AutoField(primary_key=True, serialize=False)),
                ('cd_curso', models.IntegerField()),
                ('cd_turno', models.IntegerField()),
                ('cd_disciplina', models.IntegerField()),
                ('cd_turma', models.IntegerField()),
                ('cd_professor', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id_professor', models.AutoField(primary_key=True, serialize=False)),
                ('nm_professor', models.CharField(max_length=100, verbose_name='Nome do Professor')),
                ('matricula', models.CharField(max_length=50)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grades.Disciplina')),
                ('disponibilidades', models.ManyToManyField(blank=True, to='grades.Disponibilidade')),
            ],
        ),
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id_semestre', models.AutoField(primary_key=True, serialize=False)),
                ('qtd_aula_semanal', models.IntegerField()),
                ('semestre', models.IntegerField(choices=[(1, '1ºSemestre'), (2, '2ºSemestre'), (3, '3ºSemestre'), (4, '4ºSemestre'), (5, '5ºSemestre'), (6, '6ºSemestre'), (7, '7ºSemestre'), (8, '8ºSemestre'), (9, '9ºSemestre'), (10, '10ºSemestre')], verbose_name='SEMESTRE')),
                ('cd_curso', models.IntegerField(verbose_name=grades.models.Curso)),
                ('cd_disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grades.Disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id_turma', models.AutoField(primary_key=True, serialize=False)),
                ('ds_turma', models.CharField(max_length=20)),
                ('cd_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grades.Curso')),
                ('cd_disciplinas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grades.Disciplina')),
                ('cd_professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grades.Professor')),
                ('cd_semestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grades.Semestre')),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id_turno', models.AutoField(primary_key=True, serialize=False)),
                ('cd_turno', models.CharField(choices=[('M', 'Matutino'), ('V', 'Vespertino'), ('N', 'Noturno')], max_length=1, verbose_name='Turno')),
                ('dia_semana', models.CharField(choices=[('SEG', 'Segunda-Feira'), ('TER', 'Terça-Feira'), ('QUA', 'Quarta-Feira'), ('QUI', 'Quinta-Feira'), ('SEX', 'Sexta-Feira'), ('SAB', 'Sábado')], max_length=3, verbose_name='Dia da Semana')),
                ('qtd_aulas_dia', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='turma',
            name='cd_turno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grades.Turno'),
        ),
        migrations.AddField(
            model_name='semestre',
            name='cd_turno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grades.Turno'),
        ),
        migrations.AddField(
            model_name='professor',
            name='turno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grades.Turno'),
        ),
        migrations.AddField(
            model_name='disponibilidade',
            name='turno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grades.Turno'),
        ),
    ]
