# Generated by Django 2.1.3 on 2018-11-12 02:16

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0003_auto_20181111_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='dia_semana',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('SEG', 'Segunda-Feira'), ('TER', 'Terça-Feira'), ('QUA', 'Quarta-Feira'), ('QUI', 'Quinta-Feira'), ('SEX', 'Sexta-Feira'), ('SAB', 'Sábado')], max_length=23, verbose_name='Dia da Semana'),
        ),
    ]
