# Generated by Django 2.1.3 on 2018-11-12 03:09

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0005_auto_20181112_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='sigla_disciplina',
            field=multiselectfield.db.fields.MultiSelectField(max_length=200, verbose_name='Sigla da Disciplina'),
        ),
    ]
