# Generated by Django 2.1.3 on 2018-11-12 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0006_auto_20181112_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='nm_disciplina',
            field=models.CharField(max_length=50, verbose_name='Nome da Disciplina'),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='sigla_disciplina',
            field=models.CharField(max_length=5, verbose_name='Sigla da Disciplina'),
        ),
    ]
