# Generated by Django 2.1.3 on 2018-11-19 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0009_auto_20181118_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turno',
            name='dia_semana',
        ),
        migrations.AddField(
            model_name='turno',
            name='cd_dia',
            field=models.CharField(default=-1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turno',
            name='ds_dia',
            field=models.CharField(default=-1, max_length=30, verbose_name='Dias da Semana'),
            preserve_default=False,
        ),
    ]
