# Generated by Django 2.1.3 on 2018-11-19 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0010_auto_20181119_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turno',
            name='cd_dia',
        ),
        migrations.RemoveField(
            model_name='turno',
            name='ds_dia',
        ),
        migrations.AddField(
            model_name='turno',
            name='dia_semana',
            field=models.CharField(choices=[('1', 'Domingo-Feira'), ('2', 'Segunda-Feira'), ('3', 'Terça-Feira'), ('4', 'Quarta-Feira'), ('5', 'Quinta-Feira'), ('6', 'Sexta-Feira'), ('7', 'Sábado')], default=-1, max_length=100, verbose_name='Dia da Semana'),
            preserve_default=False,
        ),
    ]
