# Generated by Django 2.1.3 on 2018-11-19 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0011_auto_20181119_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dias',
            fields=[
                ('id_turno', models.AutoField(primary_key=True, serialize=False)),
                ('dia_semana', models.CharField(max_length=30, verbose_name='Dias da Semana')),
                ('qtd_aulas', models.IntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='turno',
            options={},
        ),
        migrations.RemoveField(
            model_name='turno',
            name='cd_turno',
        ),
        migrations.RemoveField(
            model_name='turno',
            name='dia_semana',
        ),
        migrations.RemoveField(
            model_name='turno',
            name='qtd_aulas_dia',
        ),
        migrations.AddField(
            model_name='turno',
            name='turno',
            field=models.CharField(default=-1, max_length=20, verbose_name='Turno'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='disponibilidade',
            name='dia_semana',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Disponibilidade_dia_semana', to='grades.Dias'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='nm_professor',
            field=models.CharField(max_length=100, verbose_name='Professor'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='id_turno',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='turno',
            name='dias',
            field=models.ManyToManyField(related_name='turno_dias', to='grades.Dias'),
        ),
    ]
