# Generated by Django 2.1.3 on 2018-11-19 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0012_auto_20181119_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='dias',
            field=models.ManyToManyField(blank=True, related_name='turno_dias', to='grades.Dias'),
        ),
    ]
