# Generated by Django 2.1.3 on 2018-11-19 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0013_auto_20181119_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dias',
            name='dia_semana',
            field=models.CharField(blank=True, max_length=30, verbose_name='Dia da Semana'),
        ),
    ]
