# Generated by Django 2.1.3 on 2018-11-19 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0015_auto_20181119_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dias',
            name='dia_semana',
            field=models.CharField(default=-1, max_length=30, verbose_name='Dia da Semana'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dias',
            name='qtd_aulas',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
