# Generated by Django 2.1.3 on 2018-11-20 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0016_auto_20181119_2021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dias',
            old_name='id_turno',
            new_name='id_dia',
        ),
        migrations.RemoveField(
            model_name='dias',
            name='qtd_aulas',
        ),
        migrations.RemoveField(
            model_name='semestre',
            name='qtd_aula_semanal',
        ),
        migrations.RemoveField(
            model_name='turma',
            name='cd_turno',
        ),
        migrations.AddField(
            model_name='dias',
            name='qtd_aulas_dia',
            field=models.IntegerField(blank=True, null=True, verbose_name='Qtd. aulas por dia'),
        ),
        migrations.AddField(
            model_name='semestre',
            name='aula_semana',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='grades.Dias', verbose_name='Dia da semana'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='disponibilidade',
            name='dia_semana',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Disponibilidade_dia_semana', to='grades.Dias', to_field='id_turno'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='cd_curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grades.Curso', verbose_name='Curso'),
        ),
        migrations.RemoveField(
            model_name='turma',
            name='cd_disciplinas',
        ),
        migrations.AddField(
            model_name='turma',
            name='cd_disciplinas',
            field=models.ManyToManyField(to='grades.Disciplina'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='cd_professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grades.Professor', verbose_name='Professor'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='cd_semestre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grades.Semestre', verbose_name='Semestre'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='ds_turma',
            field=models.CharField(max_length=20, verbose_name='Turma'),
        ),
    ]
