# Generated by Django 2.1.3 on 2018-11-20 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0017_auto_20181120_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='dia_semana',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Disponibilidade_dia_semana', to='grades.Dias'),
        ),
        migrations.RemoveField(
            model_name='professor',
            name='disciplina',
        ),
        migrations.AddField(
            model_name='professor',
            name='disciplina',
            field=models.ManyToManyField(to='grades.Disciplina', verbose_name='Que aulas o professor ministrará?'),
        ),
        migrations.RemoveField(
            model_name='professor',
            name='turno',
        ),
        migrations.AddField(
            model_name='professor',
            name='turno',
            field=models.ManyToManyField(to='grades.Turno', verbose_name='Em quais turno?'),
        ),
    ]
