# Generated by Django 2.1.3 on 2018-11-21 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0018_auto_20181120_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='disciplina',
            field=models.ManyToManyField(to='grades.Disciplina', verbose_name='Quais aulas o professor ministrará?'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='disponibilidades',
            field=models.ManyToManyField(blank=True, to='grades.Disponibilidade'),
        ),
        migrations.AlterUniqueTogether(
            name='professor',
            unique_together={('nm_professor', 'matricula')},
        ),
        migrations.AlterUniqueTogether(
            name='turno',
            unique_together={('turno',)},
        ),
    ]
