# Generated by Django 2.1.3 on 2018-11-25 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0019_auto_20181121_0304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='disciplina',
            field=models.ManyToManyField(to='grades.Disciplina'),
        ),
        migrations.AlterUniqueTogether(
            name='dias',
            unique_together={('dia_semana',)},
        ),
    ]
