# Generated by Django 2.1.2 on 2018-11-28 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0021_auto_20181127_2304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professor',
            old_name='disciplina',
            new_name='disciplinas',
        ),
    ]
