# Generated by Django 2.1.2 on 2018-11-28 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0023_auto_20181127_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='disciplinas',
            field=models.ManyToManyField(related_name='disciplinas', to='grades.Disciplina'),
        ),
    ]
