# Generated by Django 2.1.2 on 2018-11-28 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0025_auto_20181128_0141'),
    ]

    operations = [

    ]
