# Generated by Django 2.1.2 on 2018-11-28 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0026_auto_20181128_0151'),
    ]

    operations = [
        migrations.AddField(
            model_name='disponibilidade',
            name='dia_semana',
            field=models.ManyToManyField(related_name='Disponibilidade_dia_semana', to='grades.Dias'),
        ),
    ]
