# Generated by Django 2.1.2 on 2018-11-28 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0027_auto_20181128_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='dia_semana',
            field=models.ManyToManyField(default=-1, related_name='Disponibilidade_dia_semana', to='grades.Dias'),
        ),
        migrations.AlterField(
            model_name='disponibilidade',
            name='professores',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='grades.Professor'),
        ),
    ]
