# Generated by Django 2.1.2 on 2018-11-28 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0028_auto_20181128_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='dia_semana',
            field=models.ManyToManyField(related_name='Disponibilidade_dia_semana', to='grades.Dias'),
        ),
    ]
