# Generated by Django 2.1.2 on 2018-11-28 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0030_auto_20181128_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='dia_semana',
            field=models.ManyToManyField(related_name='Disponibilidade_dia_semana', to='grades.Dias'),
        ),
    ]
