# Generated by Django 2.1.2 on 2018-11-28 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0031_auto_20181128_0308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disponibilidade',
            name='dia_semana',
        ),
    ]
