# Generated by Django 2.1.3 on 2018-11-28 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0033_auto_20181128_0311'),
    ]
    operations = [
        migrations.AlterUniqueTogether(
            name='dias',
            unique_together={('dia_semana',)},
        ),
    ]
