# Generated by Django 2.1.3 on 2018-12-02 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0037_auto_20181202_1319'),
    ]

    operations = [

    ]
