# Generated by Django 2.1.3 on 2018-12-02 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0038_auto_20181202_1345'),
    ]

    operations = [

    ]
