# Generated by Django 2.1.3 on 2018-12-03 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0039_auto_20181202_1348'),
    ]

    operations = [

    ]
