# Generated by Django 2.1.3 on 2018-12-04 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0040_auto_20181203_2034'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='semestre',
            options={'ordering': ['semestre']},
        ),

        migrations.AlterField(
            model_name='disciplina',
            name='nm_disciplina',
            field=models.CharField(max_length=50, verbose_name='Descrição da Disciplina'),
        ),
        migrations.AlterField(
            model_name='semestre',
            name='semestre',
            field=models.IntegerField(choices=[(1, '1º Semestre'), (2, '2º Semestre'), (3, '3º Semestre'), (4, '4º Semestre'), (5, '5º Semestre'), (6, '6º Semestre'), (7, '7º Semestre'), (8, '8º Semestre'), (9, '9º Semestre'), (10, '10ºSemestre')], verbose_name='SEMESTRE'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='ds_turma',
            field=models.CharField(max_length=20, unique=True, verbose_name='Descrição da Turma'),
        ),
    ]
